### ISSUE TITLE
[generator] Omit gommon_generated.go if it is empty

### ISSUE THREAD

**Issue by at15** [dyweb/gommon#77]
Current I have the following project layout where `version.go` is copied to all the binary folders

````
cmd
   version.go
   gommon_generated.go
  gommon.yaml
  tool-1
      main.go
  tool-2
      main.go
````

````yaml
# FIXME: gommon is generating empty gommon_generated.go ....
shells:
# copy version.go since it's same for all binaries
- code: echo tool-1 tool-2 | xargs -n 1 cp version.go
  shell: true
  cd: true
````

The problem is the generated `gommon_generated.go` has package `cmd` because gommon induct it based on folder name while `version.go` has `main` package 

TODO

- [ ] in generator, if there is no go file to generate, it will omit the `gommon_generated.go` file
- [ ] Allow config package name of generate go file, not all non main packages use their folder name as package name
